# Numpy

- used for n dimensional array
- It provides support for large, multi-dimensional arrays and matrices

## About Numpy

- NumPy (Numerical Python) is a powerful open-source library for numerical and scientific computing in Python.
-  It’s widely used in data science, machine learning, deep learning, and engineering
-  it provides tools to handle large multi-dimensional arrays and matrices, along with a rich collection of mathematical functions.

# Why Numpy

NumPy is a fundamental package for numerical computing in Python, and it is widely used in fields like data science, machine learning, scientific computing, and more. Here are some key reasons why NumPy is so popular:

1. Efficient Multidimensional Array Operations
2. Convenience and Flexibility
3. Mathematical and Statistical Operations
4. Compatibility with Other Libraries
5. Widely Used in Machine Learning and Data Science

NumPy is widely adopted for its:

- Speed and memory efficiency for large data sets,
- Ease of use for array manipulation and numerical computations,
- Rich functionality for mathematical operations, random number generation, and linear algebra,
- Seamless integration with other Python libraries.

# History Numpy:

- NumPy is an open source project that enables numerical computing with Python.
- It was created in 2005 building on the early work of the Numeric and Numarray libraries.
- NumPy will always be 100% open source software and free for all to use.
-  It is released under the liberal terms of the modified BSD license.

- Creation:
   Travis Oliphant created NumPy in 2005. 
 
- Building blocks:

   NumPy was built on the work of the Numeric and Numarray libraries. Numeric was the first to provide numerical methods for Python, and Numarray was an improved re-implementation of Numeric. 
 
- Unification:

   Oliphant wanted to unify the community around a single array package, so he ported Numarray's features to Numeric and released NumPy 1.0 in 2006. 
 
- Open source:

  NumPy is an open source project that's free to use. It's developed on GitHub through the consensus of the NumPy community. 
 
- Use cases: 
   NumPy is used by scientists, engineers, and other professionals around the world. For example, it's used in scripts that analyze gravitational waves and in the M87 black hole imaging project

# Advantages:

- Memory and storage : NumPy uses less memory and storage space than regular Python lists.
- Speed : NumPy is faster than regular Python lists and performs well on large datasets.
- Multi-dimensional arrays : NumPy can be used as a container for multi-dimensional arrays of generic data.
- Data manipulation : NumPy allows you to manipulate, transpose, and reshape data in matrices.
- Integration : NumPy can integrate with a variety of databases because it allows you to define arbitrary data types.

In [12]:
!pip install numpy

In [13]:
import numpy as np

# Creating a array

In [15]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [16]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
import numpy as np 
c=np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]])
print(c)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 2 3]]]]


In [19]:
c=np.array([[[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[1,2,3]]]]])
print(c)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]
    [1 2 3]
    [1 2 3]]]]]


In [20]:
c=np.array([[[[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[1,2,3],[12,34,21]]]]]])
print(c)

[[[[[[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [ 1  2  3]
     [ 1  2  3]
     [12 34 21]]]]]]


# Initial Placeholder:

1. Zeros():

- Two create an entire array with zeros 

In [24]:
c=np.zeros([3,4,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [25]:
c=np.zeros([1,2,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [26]:
c=np.zeros([3,2,2]) # syntax : shape,rows,colums
print(c)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [27]:
c=np.zeros([2,2,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [28]:
c=np.zeros([1,2,2,3]) # syntax : shape,rows,colums
print(c)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [29]:
c=np.zeros([1,2,2,3,4]) # syntax : shape,rows,colums
print(c)

[[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]]]


In [30]:
c=np.zeros([1,1,2,1,2,1]) # syntax : shape,rows,colums
print(c)

[[[[[[0.]
     [0.]]]


   [[[0.]
     [0.]]]]]]


2.for ones:

- Two create an entire array with ones

In [33]:
b=np.ones([2,3,4]) # shape,row,column
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [34]:
b=np.ones([1,3,4]) # shape,row,column
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
b=np.ones([3,4]) # shape,row,column
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
c=np.ones([1,2,2,3]) # syntax : shape,rows,colums
print(c)

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]


In [37]:
c=np.ones([1,1,2,1,2,1]) # syntax : shape,rows,colums
print(c)

[[[[[[1.]
     [1.]]]


   [[[1.]
     [1.]]]]]]


In [38]:
c=np.ones([2,2,3]) # syntax : shape,rows,colums
print(c)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


3.for creating evenly spaced values:

In [40]:
d=np.arange(1,20,5)  # [start value,end value,step]
print(d)              #[step = n-1,  5-1=4] skips 4 values and print the next value 

[ 1  6 11 16]


In [41]:
d=np.arange(1,10,6)  # [start value,end value,step]
print(d)              #[step = n-1,  6-1=5] skips 4 values and print the next value 

[1 7]


In [42]:
d=np.arange(1,15,3)  # [start value,end value,step]
print(d)              #[step = n-1,  3-1=2] skips 4 values and print the next value 

[ 1  4  7 10 13]


In [43]:
d=np.arange(1,100,2)  # [start value,end value,step]
print(d)              #[step = n-1,  2-1=1] skips 4 values and print the next value 

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


4.for evenly spaced samples:

In [45]:
s=np.linspace(1,10,4)     # [starting,ending , how many ]
print(s)

[ 1.  4.  7. 10.]


In [46]:
s=np.linspace(1,100,20)     # [starting,ending , how many ]
print(s)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [47]:
s=np.linspace(1,15,2)     # [starting,ending , how many times ]
print(s)

[ 1. 15.]


In [48]:
s=np.linspace(1,16,20)     # [starting,ending , how many times ]
print(s)

[ 1.          1.78947368  2.57894737  3.36842105  4.15789474  4.94736842
  5.73684211  6.52631579  7.31578947  8.10526316  8.89473684  9.68421053
 10.47368421 11.26315789 12.05263158 12.84210526 13.63157895 14.42105263
 15.21052632 16.        ]


In [49]:
s=np.linspace(1,150,20)     # [starting,ending , how many times ]
print(s)

[  1.           8.84210526  16.68421053  24.52631579  32.36842105
  40.21052632  48.05263158  55.89473684  63.73684211  71.57894737
  79.42105263  87.26315789  95.10526316 102.94736842 110.78947368
 118.63157895 126.47368421 134.31578947 142.15789474 150.        ]


In [50]:
import numpy as np

5.Create a 1D array :

In [52]:
e=np.full((2),4)    #2 is columns
print(e)

[4 4]


In [53]:
e=np.full((3),3)
print(e)

[3 3 3]


In [54]:
d=np.full((10),4)
print(d)

[4 4 4 4 4 4 4 4 4 4]


6.create 2D array:

In [56]:
a=np.full((2,3),5)
print(a)
print(a.ndim)

[[5 5 5]
 [5 5 5]]
2


In [57]:
a=np.full((3,3),5)
print(a)
print(a.ndim)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
2


In [58]:
a=np.full((4,3),5)
print(a)
print(a.ndim)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
2


7.Create a 3D array:

In [60]:
f=np.full((3,4,5),10)
print(f)

[[[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]]


In [61]:
f=np.full((4,4,5),4)
print(f)

[[[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]]


In [62]:
f=np.full((2,2,2),2)
print(f)

[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]]


Create 4 D array

In [64]:
f=np.full((1,1,3,2),4)
print(f)

[[[[4 4]
   [4 4]
   [4 4]]]]


In [65]:
f=np.full((1,2,3,4),5)
print(f)

[[[[5 5 5 5]
   [5 5 5 5]
   [5 5 5 5]]

  [[5 5 5 5]
   [5 5 5 5]
   [5 5 5 5]]]]


Create 5D array

In [67]:
f=np.full((1,1,2,2,4),4)
print(f)

[[[[[4 4 4 4]
    [4 4 4 4]]

   [[4 4 4 4]
    [4 4 4 4]]]]]


In [68]:
f=np.full((1,1,1,2,5),4)
print(f)

[[[[[4 4 4 4 4]
    [4 4 4 4 4]]]]]


Create a 6D array

In [70]:
f=np.full((1,1,1,1,5,6),4)
print(f)

[[[[[[4 4 4 4 4 4]
     [4 4 4 4 4 4]
     [4 4 4 4 4 4]
     [4 4 4 4 4 4]
     [4 4 4 4 4 4]]]]]]


8.create a 2*2 identity matrix:

In [72]:
e=np.eye(2)      # only for 2D
print(e)

[[1. 0.]
 [0. 1.]]


In [73]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [75]:
e=np.eye(4,2)
print(e)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [76]:
e=np.eye(2,2)
print(e)

[[1. 0.]
 [0. 1.]]


9.create a array with random numbers:

In [78]:
e=np.random.random((2,2)) # gives the value between 0 to 1
print(e)

[[0.55290128 0.14718781]
 [0.24673934 0.70520491]]


In [79]:
e=np.random.random((2,2,2,2))     
print(e)

[[[[0.25277065 0.8480853 ]
   [0.46778468 0.13897162]]

  [[0.23466797 0.80177075]
   [0.06309586 0.54500551]]]


 [[[0.79840138 0.10280355]
   [0.78844995 0.27161635]]

  [[0.37158226 0.99705966]
   [0.52410107 0.89455309]]]]


In [80]:
e=np.random.random((1,1,2,2,2))     
print(e)

[[[[[0.71658047 0.74762335]
    [0.33985299 0.09285716]]

   [[0.82851699 0.00552733]
    [0.28263357 0.49853983]]]]]


In [81]:
e=np.random.random((1,1,1,1,2,3))     
print(e)

[[[[[[0.02536004 0.00912229 0.08183593]
     [0.11843171 0.35600515 0.83848798]]]]]]


10.Create a random value within the range:

In [83]:
e=np.random.randint(1,20)    # till the range og 20
print(e)

8


In [84]:
e=np.random.randint(1,100)
print(e)

2


11.To find the shape of array:

In [86]:
a=np.array([1,2,3,4])
print(a.shape)

(4,)


In [87]:
a=np.array([[1,2,3],
            [5,6,7],
           [5,6,7]])
print(a.shape)

(3, 3)


In [88]:
a=np.array([[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2]]])
print(a.shape)

(1, 4, 3)


In [89]:
a=np.array([[[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2],
            [1,3,2]]]])
print(a.shape)

(1, 1, 5, 3)


In [90]:
a=np.array([[[[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2],
            [1,3,2],
             [21,3,2]]]]])
print(a.shape)

(1, 1, 1, 6, 3)


In [91]:
a=np.array([[[[[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2],
            [1,3,2],
             [21,3,2],
              [2,3,4]]]]]])
print(a.shape)

(1, 1, 1, 1, 7, 3)


12.To find the no of elements in an array:

In [93]:
a=np.array([[1,2,3],         
            [5,6,7],
           [5,6,7]])
print(a.size)                 

9


In [94]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(a.size)

8


In [95]:
a=np.array([[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2]]])
print(a.size)

12


In [96]:
a=np.array([[[[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2],
            [1,3,2],
             [21,3,2]]]]])
print(a.size)

18


In [508]:
a=np.array([[[[[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2],
            [1,3,2],
            [21,3,2],
            [2,3,4]]]]]])
print(a.size)

21


13.To find the length of array:

In [99]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
len(a)                       # output will be rows

2

In [100]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [5,6,7,8],
            [5,6,7,8]])
print(len(a))

4


In [101]:
a=np.array([[[1,2,3],
            [5,6,7],
            [5,6,7],
            [4,3,2]]])
len(a)

1

# Access Array Element

- you can access an array elements by referring its index number.
- same,indexes start with 0
- first element has index 0


In [104]:
arr=np.array([1,2,3,4,5])
print(arr[3])  #index

4


In [105]:
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [106]:
# for arithemetic operator

arr=np.array([1,2,3,4,5])
print(arr[3]+arr[2]+arr[1])

9


In [107]:
arr=np.array([1,2,3,4,5])
print(arr[3]+arr[2]-arr[1])

5


In [108]:
# accessing 2D array

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[2,2])

9


In [109]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1,2])

6


In [110]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0,0]) #row,col

1


In [111]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0,2])          #(row,index)

3


In [112]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             [5,6,7]])
print(arr[2,2])     #(row,index)

9


In [113]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             [5,6,7]])
print(arr[3,2])       #(row,index)

7


In [114]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             [5,6,7]])
print(arr[3,1])       #(row,index)

6


In [115]:
# Accessing 3D array:
                 #0       #1
arr=np.array([[[1,2,3],[4,5,6]],     #0
              [[7,8,9],[10,11,12]],  #1
              [[13,14,15],[16,17,18]]]) #2

print(arr[2,1,2])     #(row,colu,index)

18


In [116]:
                 #0       #1
arr=np.array([[[1,2,3],[4,5,6]],     #0
              [[7,8,9],[10,11,12]],  #1
              [[13,14,15],[16,17,18]]]) #2

print(arr[0,1,2])   #(row,colu,index)

6


In [117]:
                 #0       #1         #2
arr=np.array([[[1,2,3],[4,5,6],[34,54,21]],    #0
              [[7,8,9],[10,11,12],[43,21,34]],  #1
              [[13,14,15],[16,17,18],[56,78,9]]]) #2

print(arr[0,2,2]+arr[2,2,2]*arr[2,1,1])  #(row,colu,index)

174


In [118]:
                 #0       #1         #2
arr=np.array([[[1,2,3],[4,5,6],[34,54,21]],    #0
              [[7,8,9],[10,11,12],[43,21,34]],  #1
              [[13,14,15],[16,17,18],[56,78,9]]]) #2

print(arr[0,1,2]+arr[1,2,2]-arr[2,1,1])   #(row,colu,index)

23


In [119]:
arr = np.array([[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]],
                 
                [[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]])
print(arr[1,1,2,2])

34


In [120]:
arr = np.array([[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]], 
                 
               [[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]])

print(arr[1, 0, 1, 2, 0])

43


In [121]:
arr = np.array([[[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]]])
print(arr[0,0,0,1,2,1])

21


# Data Types:

- Numpy has some extra data types and refers to which data type with one characters,like i is for intergers, u for unsigned interger etc
- Here are the list of all data types in Numpy and the characters used to represent them

  i-integers
                         
  b-boolean
  
  f-float
  
  c-complex float
  
  M-datatime
  
  O-object
  
  S-string

In [124]:
import numpy as np

In [125]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [126]:
arr=np.array([1.2,2.3,3.5,4.2,5.0])
print(arr.dtype)

float64


In [127]:
arr=np.array([True,False,True,False])
print(arr.dtype)

bool


In [128]:
a=np.array([3+2j,3.3+4.5j])
print(a.dtype)

complex128


In [129]:
b = np.array(['2024-11-13'])
print(b.dtype)

<U10


In [130]:
b = np.array(['2024-11-13'], dtype='datetime64')
print(b.dtype) 
print(b)      

datetime64[D]
['2024-11-13']


# converting the data types

In [132]:
arr=np.array([1.2,2.3,3.5,4.2,5.0],dtype='i')
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5]


In [133]:
arr=np.array([1.2,2.3,3.5,4.2,5.0],dtype='f')
print(arr.dtype)
print(arr)

float32
[1.2 2.3 3.5 4.2 5. ]


In [134]:
arr=np.array([1,2,3,4,5],dtype='f')
print(arr.dtype)
print(arr)

float32
[1. 2. 3. 4. 5.]


In [135]:
arr=np.array([True,False,True,False],dtype='i')
print(arr.dtype)

int32


In [136]:
a=np.array([1, 0, 3, 0, 2, 0])
b=a.astype(bool)
print(a)
print(b)

[1 0 3 0 2 0]
[ True False  True False  True False]


In [137]:
arr=np.array([1,2,3,4,5])
b=a.astype(float)
print(a)
print(b)

[1 0 3 0 2 0]
[1. 0. 3. 0. 2. 0.]


In [138]:
arr=np.array([1.2,2.3,3.5,4.2,5.0])
b=arr.astype(int)
print(arr)
print(b)

[1.2 2.3 3.5 4.2 5. ]
[1 2 3 4 5]


# copy method

In [140]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[2]=32
print(a)
print(x)

[ 1  2 32  4  5]
[1 2 3 4 5]


In [141]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=12
print(a)
print(x)

[12  2  3  4  5]
[1 2 3 4 5]


In [142]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=12
a[1]=23
a[2]=32
a[3]=45
a[4]=54
print(a)
print(x)

[12 23 32 45 54]
[1 2 3 4 5]


In [143]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=12
a[1]=23
a[4]=54
print(a)
print(x)

[12 23  3  4 54]
[1 2 3 4 5]


In [144]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             [5,6,7]])
x=arr.copy()
arr[0,1]=23
print(x)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 7]]
[[ 1 23  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  6  7]]


In [145]:
                 #0       #1
arr=np.array([[[1,2,3],[4,5,6]],     #0
              [[7,8,9],[10,11,12]],  #1
              [[13,14,15],[16,17,18]]]) #2
x=arr.copy()
arr[0,1,1]=23
print(x)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4 23  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [146]:
                 #0       #1
arr=np.array([[[1,2,3],[4,5,6]],     #0
              [[7,8,9],[10,11,12]],  #1
              [[13,14,15],[16,17,18]]]) #2
x=arr.copy()
arr[2,1,0]=45
print(x)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [45 17 18]]]


In [147]:
                    #0          #1            #2
arr = np.array([[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    #0
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],  #1
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]], #2
                 
                [[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    #0
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],  #1
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]) #2
x=arr.copy()
arr[0,1,1,1]=23
print(x)
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]]
[[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 23 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]]


In [148]:
arr = np.array([[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]], 
                 
               [[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]])
x=arr.copy()
arr[1,0,1,0,1]=45
print(x)
print(arr)

[[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]



 [[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]
[[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]



 [[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7 45  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]


In [149]:
arr = np.array([[[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]]])
x=arr.copy()
arr[0,0,0,1,0,2]=23
print(x)

print(arr)

[[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8  9]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]
[[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8 23]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]


# View method

In [151]:
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=12
a[1]=23
a[4]=54
print(a)
print(x)

[12 23  3  4 54]
[12 23  3  4 54]


In [152]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             [5,6,7]])
x=arr.view()
arr[0,1]=23
print(x)

print(arr)

[[ 1 23  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  6  7]]
[[ 1 23  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  6  7]]


In [153]:
                 #0       #1
arr=np.array([[[1,2,3],[4,5,6]],     #0
              [[7,8,9],[10,11,12]],  #1
              [[13,14,15],[16,17,18]]]) #2
x=arr.view()
arr[0,1,1]=23
print(x)

print(arr)

[[[ 1  2  3]
  [ 4 23  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4 23  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [154]:
                    #0          #1            #2
arr = np.array([[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    #0
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],  #1
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]], #2
                 
                [[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    #0
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],  #1
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]) #2
x=arr.view()
arr[0,1,1,1]=23
print(x)
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 23 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]]
[[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 23 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]]


In [155]:
arr = np.array([[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]], 
                 
               [[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]])
x=arr.view()
arr[1,0,1,0,1]=45
print(x)
print(arr)

[[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]



 [[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7 45  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]
[[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]



 [[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7 45  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]


In [156]:
arr = np.array([[[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                 [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                 [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]]])
x=arr.view()
arr[0,0,0,1,0,2]=23
print(x)
print(arr)

[[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8 23]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]
[[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8 23]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]


# Reshaping arrays

- changing the shape of an array
- shape of the array: the number of elements in each dimension
- By reshaping , we can add or remove the dimensions or change the numbers of elements in each dimension
- we can use the multiples of the number of elements and change the shape
- we will reshape() function 

In [159]:
# convert 1D into 2D,3D,4D,5D,6D

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("1d:" ,array_1d)

array_2d = array_1d.reshape(2, 4)
print("2d:" ,array_2d)


array_3d = array_1d.reshape(2, 2, 2)
print("3d:" ,array_3d)


array_4d = array_1d.reshape(1, 2, 2, 2)
print("4d:" ,array_4d)

array_5d = array_1d.reshape(1, 1, 2, 2, 2)
print("5d:" ,array_5d)


array_6d = array_1d.reshape(1, 1, 1, 2, 2, 2)
print("6d:" ,array_6d)

1d: [1 2 3 4 5 6 7 8]
2d: [[1 2 3 4]
 [5 6 7 8]]
3d: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4d: [[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
5d: [[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]]
6d: [[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]]


In [160]:
#convert 2D into 3D,4D,5D,6D

array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D Array:", array_2d)

array_3d = array_2d.reshape(1, 2, 4)
print("\n3D Array:", array_3d)

array_4d = array_2d.reshape(1, 1, 2, 4)
print("\n4D Array:", array_4d)


array_5d = array_2d.reshape(1, 1, 1, 2, 4)
print("\n5D Array:", array_5d)

array_6d = array_2d.reshape(1, 1, 1, 1, 2, 4)
print("\n6D Array:", array_6d)

2D Array: [[1 2 3 4]
 [5 6 7 8]]

3D Array: [[[1 2 3 4]
  [5 6 7 8]]]

4D Array: [[[[1 2 3 4]
   [5 6 7 8]]]]

5D Array: [[[[[1 2 3 4]
    [5 6 7 8]]]]]

6D Array: [[[[[[1 2 3 4]
     [5 6 7 8]]]]]]


In [161]:
#convert 3D into 2D,4D,5D,6D

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:", array_3d)

array_2d = array_3d.reshape(4, 2)
print("2D Array:", array_2d)

array_4d = array_3d.reshape(1, 2, 2, 2)
print("4D Array:", array_4d)

array_5d = array_3d.reshape(1, 1, 2, 2, 2)
print("5D Array:", array_5d)

array_6d = array_3d.reshape(1, 1, 1, 2, 2, 2)
print("6D Array:", array_6d)

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2D Array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
4D Array: [[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
5D Array: [[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]]
6D Array: [[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]]


In [510]:
#convert 4D into 2D,3D,5D,6D

array_4d = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]])
print("4D Array:", array_4d)


array_2d = array_4d.reshape(6, 2) 
print("2D Array:", array_2d)

array_3d = array_4d.reshape(2, 3, 2)  
print("3D Array:", array_3d)

array_5d = array_4d.reshape(1, 1, 2, 3, 2)  
print("5D Array:", array_5d)

array_6d = array_4d.reshape(1, 1, 1, 2, 3, 2)  
print("6D Array:", array_6d)

4D Array: [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
2D Array: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
3D Array: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
5D Array: [[[[[ 1  2]
    [ 3  4]
    [ 5  6]]

   [[ 7  8]
    [ 9 10]
    [11 12]]]]]
6D Array: [[[[[[ 1  2]
     [ 3  4]
     [ 5  6]]

    [[ 7  8]
     [ 9 10]
     [11 12]]]]]]


In [512]:
# #convert 5D into 2D,3D,4D,6D

arr = np.array([[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                  [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                  [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]])

print("5D Array:", arr)

arr_2d = arr.reshape(9, 3) 
print("\n2D Array:", arr_2d)

arr_3d = arr.reshape(3, 3, 3)  
print("\n3D Array:", arr_3d)


arr_4d = arr.reshape(1, 3, 3, 3) 
print("\n4D Array:", arr_4d)

arr_6d = arr.reshape(1, 1, 1, 3, 3 ,3) 
print("\n6D Array:", arr_6d)


5D Array: [[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]

2D Array: [[ 1  2  3]
 [ 4  5  6]
 [34 54 21]
 [ 7  8  9]
 [10 11 12]
 [43 21 34]
 [13 14 15]
 [16 17 18]
 [56 78  9]]

3D Array: [[[ 1  2  3]
  [ 4  5  6]
  [34 54 21]]

 [[ 7  8  9]
  [10 11 12]
  [43 21 34]]

 [[13 14 15]
  [16 17 18]
  [56 78  9]]]

4D Array: [[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]

  [[ 7  8  9]
   [10 11 12]
   [43 21 34]]

  [[13 14 15]
   [16 17 18]
   [56 78  9]]]]

6D Array: [[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8  9]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]


In [164]:
# #convert 6D into 2D,3D,4D,5D

arr_6d = np.array([[[[[[1, 2, 3], [4, 5, 6], [34, 54, 21]],    
                      [[7, 8, 9], [10, 11, 12], [43, 21, 34]],
                      [[13, 14, 15], [16, 17, 18], [56, 78, 9]]]]]])

print("6D Array:", arr_6d)

arr_2d = arr_6d.reshape(9, 3)  
print("2D Array:", arr_2d)

arr_3d = arr_6d.reshape(3, 3, 3) 
print("3D Array:", arr_3d)

arr_4d = arr_6d.reshape(3, 1, 3, 3) 
print("4D Array:", arr_4d)

arr_5d = arr_6d.reshape(1, 1, 3, 3, 3) 
print("5D Array:", arr_5d)


6D Array: [[[[[[ 1  2  3]
     [ 4  5  6]
     [34 54 21]]

    [[ 7  8  9]
     [10 11 12]
     [43 21 34]]

    [[13 14 15]
     [16 17 18]
     [56 78  9]]]]]]
2D Array: [[ 1  2  3]
 [ 4  5  6]
 [34 54 21]
 [ 7  8  9]
 [10 11 12]
 [43 21 34]
 [13 14 15]
 [16 17 18]
 [56 78  9]]
3D Array: [[[ 1  2  3]
  [ 4  5  6]
  [34 54 21]]

 [[ 7  8  9]
  [10 11 12]
  [43 21 34]]

 [[13 14 15]
  [16 17 18]
  [56 78  9]]]
4D Array: [[[[ 1  2  3]
   [ 4  5  6]
   [34 54 21]]]


 [[[ 7  8  9]
   [10 11 12]
   [43 21 34]]]


 [[[13 14 15]
   [16 17 18]
   [56 78  9]]]]
5D Array: [[[[[ 1  2  3]
    [ 4  5  6]
    [34 54 21]]

   [[ 7  8  9]
    [10 11 12]
    [43 21 34]]

   [[13 14 15]
    [16 17 18]
    [56 78  9]]]]]


# Arithmrtic operations

In [166]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[6, 7], [9, 10]])

In [167]:
print(np.add(x,y))

[[ 7  9]
 [12 14]]


In [168]:
print(np.subtract(x,y))

[[-5 -5]
 [-6 -6]]


In [169]:
print(np.multiply(x,y))

[[ 6 14]
 [27 40]]


In [170]:
print(np.divide(x,y))

[[0.16666667 0.28571429]
 [0.33333333 0.4       ]]


In [171]:
x = np.array([[[12,32], [31, 14]]])
y = np.array([[[16,17], [9, 10]]])

In [172]:
print(x+y)

[[[28 49]
  [40 24]]]


In [173]:
print(x-y)

[[[-4 15]
  [22  4]]]


In [174]:
print(x*y)

[[[192 544]
  [279 140]]]


In [175]:
print(x/y)

[[[0.75       1.88235294]
  [3.44444444 1.4       ]]]


# Sorting Array

- putting array in an ordered sequence
- we use function sort()

In [339]:
x = np.array([[12,32,31, 14]])
print(np.sort(x))

[[12 14 31 32]]


In [331]:
a=np.array([2,3,4,43,32])
print(np.sort(a))

[ 2  3  4 32 43]


In [333]:
a=np.array([[2,3,4,43,32]])
print(np.sort(a))

[[ 2  3  4 32 43]]


In [337]:
a=np.array([[[2,3,4,43,32,41]]])
print(np.sort(a))

[[[ 2  3  4 32 41 43]]]


# Slicing array:

- taking the elements from one index to another
- we can use[start:end]
- to define step[start:end:step]
- if we dont start pass it will consider as 0
- if we didnt end it consider length of array
- if we didnt pass step, it will consider a 1

In [343]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[1:5])

[20 30 40 50]


In [345]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[1:])

[20 30 40 50 60 70]


In [347]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[:6])

[10 20 30 40 50 60]


In [353]:
# slicing for 2D

arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12]])
print(arr[0:1,0:2])

[[1 2]]


In [421]:
arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12],
               [13,14,15],[16,17,19]])
print(arr[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [437]:
arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12],
               [13,14,15],[16,17,19]])
print(arr[1:])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 19]]


In [453]:
arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12],
               [13,14,15],[16,17,19]])
print(arr[:4])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Negative slicing

In [456]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[-1])

70


In [460]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[-4:])

[40 50 60 70]


In [462]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[-4:-1])

[40 50 60]


In [468]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[:-1])

[10 20 30 40 50 60]


In [478]:
arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12],
               [13,14,15],[16,17,19]])
print(arr[-3:-1])

[[10 11 12]
 [13 14 15]]


In [492]:
print(arr[-1:, -3:])

[[16 17 19]]


In [506]:
arr = np.array([[1, 2, 3], [4, 5, 6], 
                [7, 8, 9],[10,11,12],
               [13,14,15],[16,17,19]])
print(arr[:, -2:])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]
 [17 19]]
